she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView

app_name = 'users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(), name='createAccount'),
]

she_codes_news/news/models.py
# from cProfile import label
# from email.mime import image
# from telnetlib import STATUS
# from turtle import update
from django.contrib.auth import get_user_model
from django.db import models


class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )

    pub_date = models.DateTimeField(verbose_name="Date")
    content = models.TextField()
    image_url = models.URLField(null=True, blank=True, verbose_name= "Image URL", max_length=200)



    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.title

    # def cache(self):
    #     result = urllib.request.urlretrieve(self.url)
    #     self.photo.save(
    #             os.path.basename(self.url),
    #             File(open(result[0]))
    #             )
    #     self.save()

she_codes_news/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class CustomUser(AbstractUser):
    pass

    def __str__(self):
        return self.username

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory 
# from django.utils import timezone

class StoryForm(ModelForm):
#     error_css_class = 'error-field'
#     required_css_class = 'required-field'

    title = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control",
    "placeholder": "Title"}))
    content = forms.CharField(widget=forms.Textarea(attrs={"placeholder":"Your amazing story goes here ♡"}))
    # image_url = forms.URLField(widget=forms.URLInput(attrs={'placeholder': "Image URL"}))
    # pub_date = forms.DateField(widget = forms.DateInput(format=('%m/%d/%Y'),attrs= {'id': 'date', 'class':'form-control','placeholder':'Select a date','type':'date'}),)
    

    class Meta:
        model = NewsStory
        fields = ['title','pub_date', 'content','image_url']
        widgets = {
            'pub_date': forms.DateInput(format=('%m/%d/%Y'),
            attrs={'id':'date', 'class':'form-control','placeholder':'Select a date',
            'type':'date'}),}
    
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['pub_date'].initial = timezone.now().strftime("%Y-%m-%dT%H:%M")

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ['username', 'email']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
    

        self.fields['password1'].help_text = ''
        self.fields['password2'].help_text = ''
        self.fields['username'].help_text = ''
        

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ['username', 'email']

she_codes_news/news/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import NewsStory
from .forms import StoryForm


class IndexView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all().order_by('-pub_date')[:4]
        context['all_stories'] = NewsStory.objects.all().order_by('-pub_date')
        return context


class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def form_valid(self,form):
        form.instance.author = self.request.user
        return super().form_valid(form)

she_codes_news/users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic
from .models import CustomUser
from .forms import CustomUserCreationForm


# Create your views here.

class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}

{% block content %}

<div style="text-align: center;"> 
    <aside style="width:20%;margin-left:auto;margin-right:auto;"></aside>
        <h3>Share your story with us ♡</h3><br>
        <form action="" method="post">
            {% csrf_token %}
            <!-- <table border="1"> -->
            {{ form.as_p }}
            <!-- </table> -->
            <br><br><br>
            <input type="submit" value="submit">
            <br><br><br><br>
        </form>
    </aside>
</div>

{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %}    
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}


{% block content %}
    <div style="text-align: center;"> 
        <aside style="width:20%;margin-left:auto;margin-right:auto;">
            <h3>Hello, {{user.username|default:'Guest'}} ♡</h3>
            {% if request.user.is_authenticated %}
                <a id = "write-new" href="{%url 'news:newStory' %}">Write New Story </a>
            {% endif %}
         </aside>
    </div>


        <h3>Latest News</h3>
    

    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include "./storyCard.html" with story=story  %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <h3>All News</h3>
    <div id="all-stories">
        {% if all_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>



{% endblock %}

she_codes_news/news/templates/news/story.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

<div id="story-wrapper" style="text-align: center;"> 
    <aside style="width:20%;margin-left:auto;margin-right:auto;"> 
        <h3>{{ story.title }}</h3>
        <img src="{{story.image_url}}">
        <!-- <img src="{% static '/news/images/placeholder-5.jpg' %}"> -->
        <h4>Written by {{ story.author }} ♡</h4>
        <!-- <div id="story-content"> -->
            
            {{ story.content|linebreaks }}
        <!-- </div> -->
    </aside>    

</div>

{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card">
    <a href="{% url 'news:story' story.id %}">
        <img src="{{story.image_url}}">

        <div class="story-card-text" style="text-align: center;">
            <h3>{{ story.title }}</h3>
            <h4>Written by {{ story.author }} ♡</h4>
            <!-- <h4>{{ story.pub_date }}</h4> -->
            <h4>Read the story</h4>
        </div>
    </a>
</div>

she_codes_news/templates/base.html
{% load static %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Madeleine Veliz">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %}{% endblock %}
    </head>

    {% include './nav.html' %}

    <body>
        <header>
            <!-- <div id="header-text"> -->
                <!-- <a id="header-link" href="{% url 'news:index' %}"> -->
                <h1 style="font-size: 10vw;">She </h1><h2 style="font-size: 10vw;"> {Codes} </h2> <h1 style="font-size: 10vw;"> News</h1>
                    
            
                <!-- </a> -->
            <!-- </div> -->

        </header>
        
        <!-- content blocks here -->
        {% block content %}{% endblock %}
    </body>
    <footer class="footer">She Codes Plus Perth, by Madeleine Veliz ©
    </footer>
</html>

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">HOME</a>
    {% if request.user.is_authenticated %}
        <!-- <a href="#">{{ user.username }}</a> -->
        <a href="#">MY ACCOUNT</a>
        <a href="{% url 'logout' %}">LOGOUT</a>
    {% else %}
        <a href="{% url 'users:createAccount' %}">CREATE ACCOUNT</a>
        <a href="{% url 'login' %}">LOGIN</a>
    {% endif %}
</nav>

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %}

{% block content %}
<div style="text-align: center;"> 
        <h3>Create Account</h3>

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <br><br>
            
                <button type="submit">Create Account</button><br><br><br>
                <!-- <p>Create your account now</p> -->
</div>
        
        </form>

{% endblock %}